#ifndef PAYLOAD_EXTRACT_PAYLOADDEFS_H
#define PAYLOAD_EXTRACT_PAYLOADDEFS_H

enum PayloadType {
	PAYLOAD_TYPE_BIN = 0,
	PAYLOAD_TYPE_ZIP,
	PAYLOAD_TYPE_URL,
};

#endif //PAYLOAD_EXTRACT_PAYLOADDEFS_H
