set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR ${MINGW_ABI})

set(CMAKE_C_COMPILER ${MINGW_SYSROOT}/bin/${MINGW_ABI}-w64-mingw32-clang)
set(CMAKE_CXX_COMPILER ${MINGW_SYSROOT}/bin/${MINGW_ABI}-w64-mingw32-clang++)
set(CMAKE_RC_COMPILER ${MINGW_SYSROOT}/bin/${MINGW_ABI}-w64-mingw32-windres)

set(CMAKE_FIND_ROOT_PATH ${MINGW_SYSROOT})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
# search headers and libraries in the target environment
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

